import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AppProvider} from "./context/AppContext"
import ConditionalLayout from "./components/ConditionalLayout"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata= {
  title: "e-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProvider>
          <ConditionalLayout>
        {children}
         </ConditionalLayout>
      </AppProvider>
      </body>
    </html>
  );
}
